version: '3.8'
services:
  # The Database
  postgres:
    image: postgres:15-alpine
    container_name: paytrans-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: paytrans
    ports:
      - "5432:5432"

  # The Tracing UI (Where you see the waterfall graphs)
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: paytrans-jaeger
    ports:
      - "16686:16686" # UI
      - "4317:4317"   # OTLP gRPC receiver