spring:
  application:
    name: paytrans-service # Renamed
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/paytrans # Renamed DB
    username: user
    password: password
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

#otel:
#  exporter:
#    otlp:
#      endpoint: http://localhost:4317
#      protocol: grpc
#  logs:
#    exporter: otlp
#  metrics:
#    exporter: otlp

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{trace_id},%X{span_id}]"

resilience4j:
  ratelimiter:
    instances:
      ingestionLimiter: # Name of our limiter
        limitForPeriod: 10          # Allow 10 requests
        limitRefreshPeriod: 1s      # Per 1 second
        timeoutDuration: 0ms        # Fail immediately (don't wait/queue)

kafka:
  bootstrap-servers: localhost:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  consumer:
    group-id: paytrans-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*" # Allow deserializing our Transaction object